"""
Phase 1045 — Guest Checkout Portal Router
==========================================

Public (no JWT), token-gated endpoints for the guest-facing checkout confirmation portal.

The guest receives a URL like:
    https://app.domaniqo.com/guest-checkout/{token}

Token type: GUEST_CHECKOUT (access_token_service.TokenType.GUEST_CHECKOUT)
Generated by: POST /bookings/{booking_id}/guest-checkout-token (admin/manager/worker)
Token lifetime: 24 hours from effective checkout date (resendable)

Design decisions (Phase 1045 audit):
  - Guest checkout confirmation is NON-BLOCKING — parallel to worker settlement.
  - booking_state.checked_out_at (worker path) remains the canonical checkout signal.
  - guest_checkout_confirmed_at is additive and informational.
  - Token is MULTI-USE (validate_and_consume NOT used — guests need repeated access).
  - VERIFY-ONLY model: HMAC + DB not-revoked + not-expired. Not one-shot consumed.
  - guest_checkout_steps_completed keys: confirm_departure, key_handover, feedback
  - feedback is always optional. confirm_departure and key_handover are primary steps.

Endpoints:
    POST /bookings/{booking_id}/guest-checkout-token  — generate + record guest checkout QR token
    GET  /guest-checkout/{token}                       — resolve token, return portal payload
    POST /guest-checkout/{token}/step/{step_key}      — submit a checkout step
    POST /guest-checkout/{token}/complete             — finalize guest checkout confirmation
"""
from __future__ import annotations

import hashlib
import logging
import os

from datetime import datetime, timezone
from typing import Any, Optional

from fastapi import APIRouter, Header
from fastapi.responses import JSONResponse

from api.error_models import ErrorCode, make_error_response

logger = logging.getLogger(__name__)

router_generate = APIRouter(tags=["guest-checkout"])  # JWT-protected (generate token)
router_portal   = APIRouter(tags=["guest-checkout"])  # Public, token-gated

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Steps presented to the guest in the checkout portal
_CHECKOUT_STEPS = [
    "confirm_departure",
    "key_handover",
    "feedback",          # optional — never blocks completion
]

_STEP_LABELS = {
    "confirm_departure": "Confirm Departure",
    "key_handover":       "Key / Access Return",
    "feedback":           "Leave Feedback (optional)",
}

_STEP_INSTRUCTIONS = {
    "confirm_departure": (
        "Please confirm that you and all guests have vacated the property "
        "and all personal belongings have been collected."
    ),
    "key_handover": (
        "Please confirm that you have returned all keys, key cards, or access devices "
        "as instructed by the host."
    ),
    "feedback": (
        "We'd love to hear about your stay. Leave a short note or rating — "
        "this is entirely optional."
    ),
}

# Roles that can generate a guest checkout token
_GENERATE_ROLES = frozenset({"admin", "manager", "ops", "worker", "checkin", "checkout"})

# Token TTL — 24h from when issued (staff can resend to refresh)
_TOKEN_TTL_SECONDS = 24 * 3600


# ---------------------------------------------------------------------------
# DB helper
# ---------------------------------------------------------------------------

def _get_db() -> Any:
    from supabase import create_client
    return create_client(
        os.environ["SUPABASE_URL"],
        os.environ["SUPABASE_SERVICE_ROLE_KEY"],
    )


def _now_iso() -> str:
    return datetime.now(tz=timezone.utc).isoformat()


def _now_ms() -> int:
    return int(datetime.now(tz=timezone.utc).timestamp() * 1000)


def _hash_token(raw_token: str) -> str:
    return hashlib.sha256(raw_token.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Identity / auth (JWT side — for generate endpoint)
# ---------------------------------------------------------------------------

def _get_identity(authorization: str) -> Optional[dict]:
    """Verify JWT and return identity dict, or None on failure."""
    try:
        from services.auth_service import verify_jwt_and_get_identity
        token = authorization.replace("Bearer ", "").strip()
        return verify_jwt_and_get_identity(token)
    except Exception:
        return None


def _assert_generate_role(identity: dict) -> Optional[JSONResponse]:
    role = identity.get("role", "")
    # Workers can have multiple roles; check canonical roles then delegated
    if role in _GENERATE_ROLES:
        return None
    # Delegated worker capabilities
    worker_roles = set((identity.get("worker_roles") or "").split(","))
    if worker_roles & {"CHECKOUT", "CHECKIN"}:
        return None
    return make_error_response(
        status_code=403, code="PERMISSION_DENIED",
        extra={"detail": f"Role '{role}' cannot generate guest checkout tokens."},
    )


# ---------------------------------------------------------------------------
# Booking fetchers
# ---------------------------------------------------------------------------

def _get_booking_for_generate(db: Any, booking_id: str, tenant_id: str) -> Optional[dict]:
    """Fetch booking_state fields needed for token generation."""
    try:
        res = (
            db.table("booking_state")
            .select(
                "booking_id, tenant_id, status, property_id, guest_name, guest_id, "
                "check_in, check_out, "
                "early_checkout_approved, early_checkout_date, early_checkout_effective_at, "
                "early_checkout_status, "
                "checked_out_at, "
                "guest_checkout_token_hash, guest_checkout_confirmed_at"
            )
            .eq("booking_id", booking_id)
            .eq("tenant_id", tenant_id)
            .limit(1)
            .execute()
        )
        rows = res.data or []
        return rows[0] if rows else None
    except Exception:
        return None


def _get_booking_for_portal(db: Any, booking_id: str) -> Optional[dict]:
    """Fetch booking_state fields for portal display (no tenant guard — token-gated)."""
    try:
        res = (
            db.table("booking_state")
            .select(
                "booking_id, tenant_id, status, property_id, guest_name, guest_id, "
                "check_in, check_out, checked_out_at, "
                "early_checkout_approved, early_checkout_date, early_checkout_effective_at, "
                "early_checkout_status, "
                "guest_checkout_initiated_at, guest_checkout_confirmed_at, "
                "guest_checkout_steps_completed, guest_checkout_token_hash"
            )
            .eq("booking_id", booking_id)
            .limit(1)
            .execute()
        )
        rows = res.data or []
        return rows[0] if rows else None
    except Exception:
        return None


def _get_property_for_portal(db: Any, property_id: str, tenant_id: str) -> Optional[dict]:
    """Fetch property display info for portal rendering."""
    try:
        res = (
            db.table("properties")
            .select(
                "property_id, display_name, name, address, city, country, "
                "checkout_time, emergency_contact, wifi_name, wifi_password"
            )
            .eq("property_id", property_id)
            .eq("tenant_id", tenant_id)
            .limit(1)
            .execute()
        )
        rows = res.data or []
        return rows[0] if rows else None
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Token verification (multi-use: verify but do NOT consume)
# ---------------------------------------------------------------------------

def _verify_guest_checkout_token(
    token: str, db: Any = None
) -> tuple[Optional[dict], Optional[str]]:
    """
    Verify a GUEST_CHECKOUT access token.
    IMPORTANT: Multi-use verification. We do NOT call validate_and_consume()
    because guests may need to re-open the portal multiple times.
    Instead: HMAC + expiry (via verify_access_token) + DB not-revoked check.
    Returns (claims_dict, None) on success, or (None, error_str) on failure.
    """
    from services.access_token_service import TokenType, verify_access_token

    claims = verify_access_token(
        token=token,
        expected_type=TokenType.GUEST_CHECKOUT,
    )
    if not claims:
        return None, "Token is invalid, expired, or has been revoked."

    # DB revocation check (without marking used_at)
    if db:
        try:
            token_hash = _hash_token(token)
            res = (
                db.table("access_tokens")
                .select("id, revoked_at")
                .eq("token_hash", token_hash)
                .eq("token_type", TokenType.GUEST_CHECKOUT.value)
                .limit(1)
                .execute()
            )
            rows = res.data or []
            if rows and rows[0].get("revoked_at"):
                return None, "This checkout link has been revoked. Contact your host for a new link."
        except Exception:
            pass  # Non-fatal: HMAC already validated

    return claims, None


# ---------------------------------------------------------------------------
# Audit helper
# ---------------------------------------------------------------------------

def _audit(
    db: Any, booking_id: str, tenant_id: str,
    action: str, actor_id: str, payload: dict,
) -> None:
    try:
        db.table("audit_events").insert({
            "booking_id":  booking_id,
            "tenant_id":   tenant_id,
            "action":      action,
            "actor_id":    actor_id,
            "payload":     payload,
            "created_at":  _now_iso(),
        }).execute()
    except Exception as exc:
        logger.warning("guest_checkout: audit write failed (non-blocking): %s", exc)


# ---------------------------------------------------------------------------
# Effective checkout date helper
# ---------------------------------------------------------------------------

def _effective_checkout_date(booking: dict) -> str:
    """Return the effective checkout date — early_checkout_date if approved, else check_out."""
    if booking.get("early_checkout_approved") and booking.get("early_checkout_date"):
        return str(booking["early_checkout_date"])[:10]
    return str(booking.get("check_out", ""))[:10]


# ===========================================================================
# POST /bookings/{booking_id}/guest-checkout-token
# JWT-protected. Generates a GUEST_CHECKOUT token for the given booking.
# ===========================================================================

@router_generate.post(
    "/bookings/{booking_id}/guest-checkout-token",
    summary="Generate guest checkout portal token (Phase 1045)",
    status_code=200,
)
async def generate_guest_checkout_token(
    booking_id: str,
    authorization: str = Header(alias="Authorization"),
    client: Optional[Any] = None,
) -> JSONResponse:
    """
    Generate a GUEST_CHECKOUT access token for a booking.

    - Callable by: admin, manager, checkin/checkout worker roles
    - Token lifetime: 24h (resendable by re-calling this endpoint)
    - Previous tokens for the same booking remain valid until they expire or are revoked
    - Records token_hash in booking_state.guest_checkout_token_hash
    - Returns: token, portal_url, expires_at, qr_data (for QR image generation)

    Body: (none required — booking_id in path)
    """
    identity = _get_identity(authorization)
    if not identity:
        return make_error_response(status_code=401, code="UNAUTHORIZED",
                                   extra={"detail": "Invalid or missing JWT."})

    err_resp = _assert_generate_role(identity)
    if err_resp:
        return err_resp

    tenant_id = identity.get("tenant_id") or identity.get("tenantId")
    if not tenant_id:
        return make_error_response(status_code=401, code="UNAUTHORIZED",
                                   extra={"detail": "Cannot determine tenant from token."})

    db = client or _get_db()
    booking = _get_booking_for_generate(db, booking_id, tenant_id)
    if not booking:
        return make_error_response(status_code=404, code=ErrorCode.NOT_FOUND,
                                   extra={"detail": "Booking not found."})

    # Guard: don't generate tokens for cancelled bookings
    booking_status = (booking.get("status") or "").upper()
    if booking_status in ("CANCELLED", "CANCELED", "REJECTED"):
        return make_error_response(
            status_code=409, code="INVALID_STATE",
            extra={"detail": f"Cannot generate checkout token for booking in status '{booking_status}'."},
        )

    from services.access_token_service import TokenType, issue_access_token, record_token

    raw_token, exp = issue_access_token(
        token_type=TokenType.GUEST_CHECKOUT,
        entity_id=booking_id,
        email=str(booking.get("guest_id") or ""),
        ttl_seconds=_TOKEN_TTL_SECONDS,
    )

    token_hash = _hash_token(raw_token)

    # Record in access_tokens table
    record_token(
        tenant_id=tenant_id,
        token_type=TokenType.GUEST_CHECKOUT,
        entity_id=booking_id,
        raw_token=raw_token,
        exp=exp,
        email=str(booking.get("guest_id") or ""),
        metadata={
            "booking_id": booking_id,
            "generated_by": identity.get("user_id") or identity.get("sub") or "unknown",
            "property_id": booking.get("property_id"),
        },
        db=db,
    )

    # Store hash in booking_state for lookup
    try:
        db.table("booking_state").update({
            "guest_checkout_token_hash": token_hash,
            "updated_at_ms": _now_ms(),
        }).eq("booking_id", booking_id).eq("tenant_id", tenant_id).execute()
    except Exception as exc:
        logger.warning("guest_checkout: booking_state token_hash update failed: %s", exc)

    # Build portal URL (frontend route)
    base_url = os.environ.get("NEXT_PUBLIC_SITE_URL", "https://domaniqo-staging.vercel.app")
    portal_url = f"{base_url}/guest-checkout/{raw_token}"
    expires_at_iso = datetime.fromtimestamp(exp, tz=timezone.utc).isoformat()
    effective_date = _effective_checkout_date(booking)

    _audit(db, booking_id, tenant_id, "GUEST_CHECKOUT_TOKEN_GENERATED",
           identity.get("user_id") or "unknown",
           {
               "generated_by": identity.get("user_id") or "unknown",
               "portal_url": portal_url,
               "expires_at": expires_at_iso,
               "effective_checkout_date": effective_date,
           })

    return JSONResponse(status_code=200, content={
        "status":        "token_issued",
        "token":         raw_token,
        "portal_url":    portal_url,
        "qr_data":       portal_url,          # QR image: encode this string
        "expires_at":    expires_at_iso,
        "effective_checkout_date": effective_date,
        "guest_name":    booking.get("guest_name") or "Guest",
        "property_id":   booking.get("property_id"),
    })


# ===========================================================================
# GET /guest-checkout/{token}
# Public, token-gated. Returns portal state.
# ===========================================================================

@router_portal.get(
    "/guest-checkout/{token}",
    summary="Load guest checkout portal state (Phase 1045)",
    status_code=200,
)
async def get_guest_checkout_portal(
    token: str,
    client: Optional[Any] = None,
) -> JSONResponse:
    """
    Load the guest checkout portal.

    Returns:
    - Booking context (property name, checkout date, guest name)
    - Step definitions + completion status
    - Property contact info for the help/fallback path
    - Current confirmation status (already_confirmed vs pending)

    Marks guest_checkout_initiated_at on first access.
    """
    db = client or _get_db()
    claims, err = _verify_guest_checkout_token(token, db=db)
    if err:
        return make_error_response(status_code=401, code="TOKEN_INVALID", extra={"detail": err})

    booking_id = claims.get("entity_id")
    if not booking_id:
        return make_error_response(status_code=401, code="TOKEN_INVALID",
                                   extra={"detail": "Token does not reference a booking."})

    booking = _get_booking_for_portal(db, booking_id)
    if not booking:
        return make_error_response(status_code=404, code=ErrorCode.NOT_FOUND,
                                   extra={"detail": "Booking not found."})

    tenant_id = booking["tenant_id"]
    property_id = booking["property_id"]
    prop = _get_property_for_portal(db, property_id, tenant_id)

    # Mark initiation timestamp on first access (non-blocking)
    if not booking.get("guest_checkout_initiated_at"):
        try:
            db.table("booking_state").update({
                "guest_checkout_initiated_at": _now_iso(),
                "updated_at_ms": _now_ms(),
            }).eq("booking_id", booking_id).eq("tenant_id", tenant_id).execute()
        except Exception:
            pass

    steps_completed = booking.get("guest_checkout_steps_completed") or {}
    effective_date = _effective_checkout_date(booking)

    # Build step list for the portal
    steps = []
    for key in _CHECKOUT_STEPS:
        steps.append({
            "key":         key,
            "label":       _STEP_LABELS[key],
            "instruction": _STEP_INSTRUCTIONS[key],
            "optional":    key == "feedback",
            "completed":   bool(steps_completed.get(key)),
            "detail":      steps_completed.get(key),
        })

    already_confirmed = bool(booking.get("guest_checkout_confirmed_at"))
    required_complete = all(
        steps_completed.get(k)
        for k in _CHECKOUT_STEPS
        if k != "feedback"   # feedback is optional
    )

    return JSONResponse(status_code=200, content={
        "booking": {
            "booking_id":      booking["booking_id"],
            "guest_name":      booking.get("guest_name") or "Guest",
            "check_in":        str(booking.get("check_in", ""))[:10],
            "check_out":       str(booking.get("check_out", ""))[:10],
            "effective_checkout_date": effective_date,
            "is_early_checkout": bool(
                booking.get("early_checkout_approved") and booking.get("early_checkout_date")
            ),
        },
        "property": {
            "name":              (prop or {}).get("display_name") or (prop or {}).get("name") or property_id,
            "address":           (prop or {}).get("address"),
            "city":              (prop or {}).get("city"),
            "country":           (prop or {}).get("country"),
            "checkout_time":     (prop or {}).get("checkout_time") or "11:00",
            "emergency_contact": (prop or {}).get("emergency_contact"),
            "wifi_name":         (prop or {}).get("wifi_name"),
            "wifi_password":     (prop or {}).get("wifi_password"),
        },
        "steps":             steps,
        "steps_completed":   steps_completed,
        "required_complete": required_complete,
        "already_confirmed": already_confirmed,
        "confirmed_at":      str(booking.get("guest_checkout_confirmed_at") or ""),
        "initiated_at":      str(booking.get("guest_checkout_initiated_at") or ""),
    })


# ===========================================================================
# POST /guest-checkout/{token}/step/{step_key}
# Public, token-gated. Mark a single checkout step complete.
# ===========================================================================

@router_portal.post(
    "/guest-checkout/{token}/step/{step_key}",
    summary="Submit a guest checkout step (Phase 1045)",
    status_code=200,
)
async def submit_checkout_step(
    token: str,
    step_key: str,
    body: dict = {},
    client: Optional[Any] = None,
) -> JSONResponse:
    """
    Mark an individual checkout step as complete.

    Valid step_key values: confirm_departure, key_handover, feedback
    Body for 'feedback': { rating?: 1-5, comment?: string }
    Body for others: (none required)

    Idempotent — re-submitting overwrites previous value.
    """
    if step_key not in _CHECKOUT_STEPS:
        return make_error_response(
            status_code=400, code="UNKNOWN_STEP",
            extra={
                "detail": f"'{step_key}' is not a valid checkout step.",
                "valid_steps": _CHECKOUT_STEPS,
            },
        )

    db = client or _get_db()
    claims, err = _verify_guest_checkout_token(token, db=db)
    if err:
        return make_error_response(status_code=401, code="TOKEN_INVALID", extra={"detail": err})

    booking_id = claims.get("entity_id")
    if not booking_id:
        return make_error_response(status_code=401, code="TOKEN_INVALID",
                                   extra={"detail": "Invalid token."})

    booking = _get_booking_for_portal(db, booking_id)
    if not booking:
        return make_error_response(status_code=404, code=ErrorCode.NOT_FOUND,
                                   extra={"detail": "Booking not found."})

    tenant_id = booking["tenant_id"]
    steps = booking.get("guest_checkout_steps_completed") or {}
    now = _now_iso()

    # Build step detail payload
    step_detail: dict = {"completed_at": now}
    if step_key == "feedback":
        rating = body.get("rating")
        comment = body.get("comment") or ""
        if rating is not None:
            try:
                r = int(rating)
                if 1 <= r <= 5:
                    step_detail["rating"] = r
            except (ValueError, TypeError):
                pass
        if comment:
            step_detail["comment"] = str(comment)[:500]
    elif step_key == "confirm_departure":
        step_detail["confirmed_by_guest"] = True
    elif step_key == "key_handover":
        method = str(body.get("method") or "confirmed")
        step_detail["method"] = method[:50]

    steps[step_key] = step_detail

    try:
        db.table("booking_state").update({
            "guest_checkout_steps_completed": steps,
            "updated_at_ms": _now_ms(),
        }).eq("booking_id", booking_id).eq("tenant_id", tenant_id).execute()
    except Exception as exc:
        logger.error("guest_checkout: step update failed: %s", exc)
        return make_error_response(status_code=500, code="SERVER_ERROR",
                                   extra={"detail": "Failed to save step. Please try again."})

    return JSONResponse(status_code=200, content={
        "status":          "step_completed",
        "step_key":        step_key,
        "steps_completed": list(steps.keys()),
    })


# ===========================================================================
# POST /guest-checkout/{token}/complete
# Public, token-gated. Finalize guest checkout confirmation.
# ===========================================================================

@router_portal.post(
    "/guest-checkout/{token}/complete",
    summary="Finalize guest checkout confirmation (Phase 1045)",
    status_code=200,
)
async def complete_guest_checkout(
    token: str,
    client: Optional[Any] = None,
) -> JSONResponse:
    """
    Guest confirms departure and finalizes the checkout portal.

    Requirements:
    - confirm_departure step must be completed
    - key_handover step must be completed
    - feedback is always optional

    Effect:
    - Writes guest_checkout_confirmed_at to booking_state
    - Emits audit event GUEST_CHECKOUT_CONFIRMED
    - Returns success payload with property name and confirmation timestamp
    - Idempotent: re-calling returns the existing confirmation timestamp

    NOTE: This does NOT affect worker settlement or booking_state.checked_out_at.
    Worker checkout proceeds independently via the ops checkout wizard.
    """
    db = client or _get_db()
    claims, err = _verify_guest_checkout_token(token, db=db)
    if err:
        return make_error_response(status_code=401, code="TOKEN_INVALID", extra={"detail": err})

    booking_id = claims.get("entity_id")
    if not booking_id:
        return make_error_response(status_code=401, code="TOKEN_INVALID",
                                   extra={"detail": "Invalid token."})

    booking = _get_booking_for_portal(db, booking_id)
    if not booking:
        return make_error_response(status_code=404, code=ErrorCode.NOT_FOUND,
                                   extra={"detail": "Booking not found."})

    tenant_id = booking["tenant_id"]

    # Idempotent: already confirmed
    existing_confirmed_at = booking.get("guest_checkout_confirmed_at")
    if existing_confirmed_at:
        return JSONResponse(status_code=200, content={
            "status":       "already_confirmed",
            "confirmed_at": str(existing_confirmed_at),
            "noop":         True,
        })

    # Validate required steps
    steps = booking.get("guest_checkout_steps_completed") or {}
    missing = [k for k in ("confirm_departure", "key_handover") if not steps.get(k)]
    if missing:
        return make_error_response(
            status_code=409, code="STEPS_INCOMPLETE",
            extra={
                "detail": "Please complete all required steps before confirming checkout.",
                "missing_steps": missing,
            },
        )

    now = _now_iso()
    try:
        db.table("booking_state").update({
            "guest_checkout_confirmed_at": now,
            "updated_at_ms": _now_ms(),
        }).eq("booking_id", booking_id).eq("tenant_id", tenant_id).execute()
    except Exception as exc:
        logger.error("guest_checkout: confirmed_at write failed: %s", exc)
        return make_error_response(status_code=500, code="SERVER_ERROR",
                                   extra={"detail": "Failed to confirm checkout. Please try again."})

    _audit(db, booking_id, tenant_id, "GUEST_CHECKOUT_CONFIRMED",
           "guest",
           {
               "confirmed_at": now,
               "steps_completed": list(steps.keys()),
               "effective_checkout_date": _effective_checkout_date(booking),
           })

    # Fetch property for the success message
    prop = _get_booking_for_portal(db, booking_id)  # Reload for response
    prop_info = _get_property_for_portal(db, booking.get("property_id", ""), tenant_id)
    property_name = (prop_info or {}).get("display_name") or (prop_info or {}).get("name") or "your property"

    return JSONResponse(status_code=200, content={
        "status":        "confirmed",
        "confirmed_at":  now,
        "guest_name":    booking.get("guest_name") or "Guest",
        "property_name": property_name,
        "message":       (
            f"Thank you for confirming your checkout from {property_name}. "
            "We hope you had a wonderful stay and look forward to welcoming you back."
        ),
    })
