"""
Phase 1045 — Guest Checkout Portal Router
==========================================

Public (no JWT), token-gated endpoints for the guest-facing checkout confirmation portal.

The guest receives a URL like:
    https://app.domaniqo.com/guest-checkout/{token}

Token type: GUEST_CHECKOUT (access_token_service.TokenType.GUEST_CHECKOUT)
Generated by: POST /bookings/{booking_id}/guest-checkout-token (admin/manager/worker)
Token lifetime: computed from effective checkout datetime + 4h grace window.
  If early_checkout_effective_at is set (precise TIMESTAMPTZ), token expires 4h after that.
  Otherwise: (check_out DATE assumed 11:00 UTC) + 4h grace = expires at ~15:00 UTC on checkout day.
  Minimum floor: 1 hour from issuance.
  Staff can re-issue at any time to refresh the token.

Design decisions (Phase 1045 audit):
  - Guest checkout confirmation is NON-BLOCKING — parallel to worker settlement.
  - booking_state.checked_out_at (worker path) remains the canonical checkout signal.
  - guest_checkout_confirmed_at is additive and informational.
  - Token is MULTI-USE (validate_and_consume NOT used — guests need repeated access).
  - VERIFY-ONLY model: HMAC + DB not-revoked + not-expired. Not one-shot consumed.
  - guest_checkout_steps_completed keys: confirm_departure, key_handover, feedback
  - feedback is always optional. confirm_departure and key_handover are primary steps.

Endpoints:
    POST /bookings/{booking_id}/guest-checkout-token  — generate + record guest checkout QR token
    GET  /guest-checkout/{token}                       — resolve token, return portal payload
    POST /guest-checkout/{token}/step/{step_key}      — submit a checkout step
    POST /guest-checkout/{token}/complete             — finalize guest checkout confirmation
"""
from __future__ import annotations

import hashlib
import logging
import os

from datetime import datetime, timezone, timedelta, date as date_type
from typing import Any, Optional

from fastapi import APIRouter, Header
from fastapi.responses import JSONResponse

from api.error_models import ErrorCode, make_error_response

logger = logging.getLogger(__name__)

router_generate = APIRouter(tags=["guest-checkout"])  # JWT-protected (generate token)
router_portal   = APIRouter(tags=["guest-checkout"])  # Public, token-gated

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Phase 1065B — Steps presented to the guest in the self checkout wizard
_CHECKOUT_STEPS = [
    "confirm_departure",
    "ac_lights",
    "doors_locked",
    "key_handover",
    "contact_confirm",
    "feedback",          # optional — never blocks completion
]

_REQUIRED_FOR_COMPLETE = frozenset({"confirm_departure", "ac_lights", "doors_locked", "key_handover", "contact_confirm"})

_STEP_LABELS = {
    "confirm_departure": "Ready to leave",
    "ac_lights":          "AC, lights & appliances",
    "doors_locked":       "Doors & windows",
    "key_handover":       "Keys & access cards",
    "contact_confirm":    "Follow-up contact",
    "feedback":           "Any final notes? (optional)",
}

_STEP_INSTRUCTIONS = {
    "confirm_departure": (
        "Please confirm that you and all guests have collected your belongings "
        "and are ready to leave the property."
    ),
    "ac_lights": (
        "Turn off the air conditioning, all lights, and any fans or appliances before you leave."
    ),
    "doors_locked": (
        "Check that all doors and windows are closed and locked before you go."
    ),
    "key_handover": (
        "Return all keys, key cards, or access devices as your host instructed "
        "(lockbox, reception counter, or leave with staff)."
    ),
    "contact_confirm": (
        "Please leave a phone number or email so the team can reach you after checkout "
        "for deposit return, electricity settlement, or any follow-up."
    ),
    "feedback": (
        "Anything you'd like to share about your stay? "
        "A short note is very helpful — entirely optional."
    ),
}

# Roles that can generate a guest checkout token
_GENERATE_ROLES = frozenset({"admin", "manager", "ops", "worker", "checkin", "checkout"})

# Token TTL — computed from effective checkout time, not a flat constant.
# See _compute_token_ttl() below.
_TOKEN_TTL_FALLBACK_SECONDS = 24 * 3600   # used only when no date data is available


# ---------------------------------------------------------------------------
# DB helper
# ---------------------------------------------------------------------------

def _get_db() -> Any:
    from supabase import create_client
    return create_client(
        os.environ["SUPABASE_URL"],
        os.environ["SUPABASE_SERVICE_ROLE_KEY"],
    )


def _now_iso() -> str:
    return datetime.now(tz=timezone.utc).isoformat()


def _now_ms() -> int:
    return int(datetime.now(tz=timezone.utc).timestamp() * 1000)


def _hash_token(raw_token: str) -> str:
    return hashlib.sha256(raw_token.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Identity / auth (JWT side — for generate endpoint)
# ---------------------------------------------------------------------------

def _get_identity(authorization: str) -> Optional[dict]:
    """Verify JWT and return identity dict, or None on failure."""
    try:
        from services.auth_service import verify_jwt_and_get_identity
        token = authorization.replace("Bearer ", "").strip()
        return verify_jwt_and_get_identity(token)
    except Exception:
        return None


def _assert_generate_role(identity: dict) -> Optional[JSONResponse]:
    role = identity.get("role", "")
    # Workers can have multiple roles; check canonical roles then delegated
    if role in _GENERATE_ROLES:
        return None
    # Delegated worker capabilities
    worker_roles = set((identity.get("worker_roles") or "").split(","))
    if worker_roles & {"CHECKOUT", "CHECKIN"}:
        return None
    return make_error_response(
        status_code=403, code="PERMISSION_DENIED",
        extra={"detail": f"Role '{role}' cannot generate guest checkout tokens."},
    )


# ---------------------------------------------------------------------------
# Booking fetchers
# ---------------------------------------------------------------------------

def _get_booking_for_generate(db: Any, booking_id: str, tenant_id: str) -> Optional[dict]:
    """Fetch booking_state fields needed for token generation."""
    try:
        res = (
            db.table("booking_state")
            .select(
                "booking_id, tenant_id, status, property_id, guest_name, guest_id, "
                "check_in, check_out, "
                "early_checkout_approved, early_checkout_date, early_checkout_effective_at, "
                "early_checkout_status, "
                "checked_out_at, "
                "guest_checkout_token_hash, guest_checkout_confirmed_at"
            )
            .eq("booking_id", booking_id)
            .eq("tenant_id", tenant_id)
            .limit(1)
            .execute()
        )
        rows = res.data or []
        return rows[0] if rows else None
    except Exception:
        return None


def _get_booking_for_portal(db: Any, booking_id: str) -> Optional[dict]:
    """Fetch booking_state fields for portal display (no tenant guard — token-gated)."""
    try:
        res = (
            db.table("booking_state")
            .select(
                "booking_id, tenant_id, status, property_id, guest_name, guest_id, "
                "check_in, check_out, checked_out_at, "
                "early_checkout_approved, early_checkout_date, early_checkout_effective_at, "
                "early_checkout_status, "
                "guest_checkout_initiated_at, guest_checkout_confirmed_at, "
                "guest_checkout_steps_completed, guest_checkout_token_hash, "
                "used_guest_self_checkout, guest_checkout_contact_phone, guest_checkout_contact_email, "
                "guest_checkout_summary, deposit_status, opening_meter"
            )
            .eq("booking_id", booking_id)
            .limit(1)
            .execute()
        )
        rows = res.data or []
        return rows[0] if rows else None
    except Exception:
        return None


def _get_checkin_photos(db: Any, booking_id: str, limit: int = 4) -> list:
    """
    Phase 1065B: Fetch a small set of check-in reference photos for the proof-photo helper.
    Shown to guests as reference so they can optionally take matching checkout photos
    for their own records.
    """
    try:
        res = (
            db.table("booking_photos")
            .select("photo_url, caption, taken_at, photo_type")
            .eq("booking_id", booking_id)
            .in_("photo_type", ["checkin", "check_in", "arrival", "opening"])
            .order("taken_at", desc=False)
            .limit(limit)
            .execute()
        )
        return [
            {"url": r.get("photo_url"), "caption": r.get("caption"), "taken_at": r.get("taken_at")}
            for r in (res.data or []) if r.get("photo_url")
        ]
    except Exception:
        return []


def _get_property_for_portal(db: Any, property_id: str, tenant_id: str) -> Optional[dict]:
    """Fetch property display info for portal rendering."""
    try:
        res = (
            db.table("properties")
            .select(
                "property_id, display_name, address, city, country, "
                "checkout_time, emergency_contact, wifi_name, wifi_password"
            )
            .eq("property_id", property_id)
            .eq("tenant_id", tenant_id)
            .limit(1)
            .execute()
        )
        rows = res.data or []
        return rows[0] if rows else None
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Token verification (multi-use: verify but do NOT consume)
# ---------------------------------------------------------------------------

def _verify_guest_checkout_token(
    token: str, db: Any = None
) -> tuple[Optional[dict], Optional[str]]:
    """
    Verify a GUEST_CHECKOUT access token.
    IMPORTANT: Multi-use verification. We do NOT call validate_and_consume()
    because guests may need to re-open the portal multiple times.
    Instead: HMAC + expiry (via verify_access_token) + DB not-revoked check.

    Phase 1065B fallback: if the token does not validate as GUEST_CHECKOUT
    (for example when the guest portal CTA passes the GUEST_PORTAL token),
    try resolving it as a GUEST_PORTAL token via resolve_guest_token_context.
    On success, synthesise a compatible claims dict so the rest of the route
    works identically regardless of which token type was supplied.

    Returns (claims_dict, None) on success, or (None, error_str) on failure.
    """
    from services.access_token_service import TokenType, verify_access_token

    # --- Path 1: proper GUEST_CHECKOUT token (normal flow) ---
    claims = verify_access_token(
        token=token,
        expected_type=TokenType.GUEST_CHECKOUT,
    )
    if claims:
        # DB revocation check (without marking used_at)
        if db:
            try:
                token_hash = _hash_token(token)
                res = (
                    db.table("access_tokens")
                    .select("id, revoked_at")
                    .eq("token_hash", token_hash)
                    .eq("token_type", TokenType.GUEST_CHECKOUT.value)
                    .limit(1)
                    .execute()
                )
                rows = res.data or []
                if rows and rows[0].get("revoked_at"):
                    return None, "This checkout link has been revoked. Contact your host for a new link."
            except Exception:
                pass  # Non-fatal: HMAC already validated
        return claims, None

    # --- Path 2: GUEST_PORTAL token fallback (Phase 1065B) ---
    # Inline verification with one unique diagnostic code per sub-step.
    # Bypasses resolve_guest_token_context() to identify the exact failure point.
    import time as _time_mod, hmac as _hmac_mod, base64 as _b64_mod, hashlib as _hl_mod
    try:
        from services.guest_token import _get_secret, _decode_token, _sign, is_guest_token_revoked
    except ImportError as _ie:
        return None, f"[diag-P2-IMPORT] {_ie}"

    try:
        _secret = _get_secret()
    except RuntimeError as _re:
        return None, f"[diag-P2-SECRET] IHOUSE_GUEST_TOKEN_SECRET not set: {_re}"

    _decoded = _decode_token(token)
    if _decoded is None:
        return None, f"[diag-P2-DECODE] no dot separator or bad base64. token[:30]={token[:30]!r}"

    _message, _provided_sig = _decoded
    _expected_sig = _sign(_message, _secret)
    if not _hmac_mod.compare_digest(_provided_sig, _expected_sig):
        return None, f"[diag-P2-HMAC] HMAC mismatch. provided[:8]={_provided_sig[:8]!r} expected[:8]={_expected_sig[:8]!r}"

    _parts = _message.split(":", 2)
    if len(_parts) != 3:
        return None, f"[diag-P2-FORMAT] message has {len(_parts)} parts, expected 3. msg={_message[:40]!r}"

    _booking_ref, _guest_email, _exp_str = _parts
    try:
        _exp = int(_exp_str)
    except ValueError:
        return None, f"[diag-P2-EXP-VAL] exp_str not an int: {_exp_str!r}"

    _now = int(_time_mod.time())
    if _exp < _now:
        return None, f"[diag-P2-EXPIRED] token expired {_now - _exp}s ago (exp={_exp}, now={_now})"

    if not _booking_ref:
        return None, f"[diag-P2-NOREF] booking_ref is empty in token message"

    logger.info("_verify_guest_checkout_token: path2 success booking_ref=%s", _booking_ref)
    return {
        "token_type": "guest_checkout",
        "entity_id":  _booking_ref,
        "email":      _guest_email or "",
        "exp":        _exp,
        "_via_portal_token": True,
    }, None





# ---------------------------------------------------------------------------
# Audit helper
# ---------------------------------------------------------------------------

def _audit(
    db: Any, booking_id: str, tenant_id: str,
    action: str, actor_id: str, payload: dict,
) -> None:
    try:
        db.table("audit_events").insert({
            "booking_id":  booking_id,
            "tenant_id":   tenant_id,
            "action":      action,
            "actor_id":    actor_id,
            "payload":     payload,
            "created_at":  _now_iso(),
        }).execute()
    except Exception as exc:
        logger.warning("guest_checkout: audit write failed (non-blocking): %s", exc)


# ---------------------------------------------------------------------------
# Effective checkout date helper
# ---------------------------------------------------------------------------

def _effective_checkout_date(booking: dict) -> str:
    """Return the effective checkout date — early_checkout_date if approved, else check_out."""
    if booking.get("early_checkout_approved") and booking.get("early_checkout_date"):
        return str(booking["early_checkout_date"])[:10]
    return str(booking.get("check_out", ""))[:10]


def _compute_token_ttl(booking: dict) -> int:
    """
    Compute guest checkout token TTL in seconds.

    Rule: token expires approximately 4 hours after the effective checkout datetime.

    Priority:
      1. early_checkout_effective_at (precise TIMESTAMPTZ, best signal)
         → token valid until that moment + 4h
      2. early_checkout_date or check_out DATE assumed at 11:00 UTC
         → token valid until (checkout date 11:00 UTC) + 4h = ~15:00 UTC
      3. Fallback: 24h from now (used only if no date data is present)

    Minimum: 1 hour from now, regardless of calculation
    (avoids issuing a token that expires immediately if staff sends late).
    """
    GRACE = timedelta(hours=4)
    MINIMUM = 3600  # 1 hour floor
    now = datetime.now(tz=timezone.utc)

    # Path 1: precise effective checkout datetime
    if booking.get("early_checkout_approved") and booking.get("early_checkout_effective_at"):
        try:
            eff_str = str(booking["early_checkout_effective_at"])
            # Handle both offset-aware and naive strings
            eff = datetime.fromisoformat(eff_str.replace("Z", "+00:00"))
            if eff.tzinfo is None:
                eff = eff.replace(tzinfo=timezone.utc)
            target = eff + GRACE
            ttl = int((target - now).total_seconds())
            return max(ttl, MINIMUM)
        except Exception:
            pass  # fall through

    # Path 2: effective checkout DATE (early or regular) at 11:00 UTC
    checkout_date_str: str = _effective_checkout_date(booking)
    if checkout_date_str:
        try:
            co = date_type.fromisoformat(checkout_date_str)
            # Assume property checkout time = 11:00 UTC (conservative; no per-property TZ data)
            checkout_dt = datetime(co.year, co.month, co.day, 11, 0, 0, tzinfo=timezone.utc)
            target = checkout_dt + GRACE
            ttl = int((target - now).total_seconds())
            return max(ttl, MINIMUM)
        except Exception:
            pass  # fall through

    # Path 3: fallback — no date data available
    logger.warning("guest_checkout: no checkout date for booking %s — using fallback TTL",
                   booking.get("booking_id", "?"))
    return _TOKEN_TTL_FALLBACK_SECONDS


# ===========================================================================
# POST /bookings/{booking_id}/guest-checkout-token
# JWT-protected. Generates a GUEST_CHECKOUT token for the given booking.
# ===========================================================================

@router_generate.post(
    "/bookings/{booking_id}/guest-checkout-token",
    summary="Generate guest checkout portal token (Phase 1045)",
    status_code=200,
)
async def generate_guest_checkout_token(
    booking_id: str,
    authorization: str = Header(alias="Authorization"),
    client: Optional[Any] = None,
) -> JSONResponse:
    """
    Generate a GUEST_CHECKOUT access token for a booking.

    - Callable by: admin, manager, checkin/checkout worker roles
    - Token lifetime: computed from effective checkout datetime + 4h grace window
      (resendable by re-calling this endpoint to reset the window)
    - Previous tokens for the same booking remain valid until they expire or are revoked
    - Records token_hash in booking_state.guest_checkout_token_hash
    - Returns: token, portal_url, expires_at, qr_data (for QR image generation)

    Body: (none required — booking_id in path)
    """
    identity = _get_identity(authorization)
    if not identity:
        return make_error_response(status_code=401, code="UNAUTHORIZED",
                                   extra={"detail": "Invalid or missing JWT."})

    err_resp = _assert_generate_role(identity)
    if err_resp:
        return err_resp

    tenant_id = identity.get("tenant_id") or identity.get("tenantId")
    if not tenant_id:
        return make_error_response(status_code=401, code="UNAUTHORIZED",
                                   extra={"detail": "Cannot determine tenant from token."})

    db = client or _get_db()
    booking = _get_booking_for_generate(db, booking_id, tenant_id)
    if not booking:
        return make_error_response(status_code=404, code=ErrorCode.NOT_FOUND,
                                   extra={"detail": "Booking not found."})

    # Guard: don't generate tokens for cancelled bookings
    booking_status = (booking.get("status") or "").upper()
    if booking_status in ("CANCELLED", "CANCELED", "REJECTED"):
        return make_error_response(
            status_code=409, code="INVALID_STATE",
            extra={"detail": f"Cannot generate checkout token for booking in status '{booking_status}'."},
        )

    from services.access_token_service import TokenType, issue_access_token, record_token

    ttl_seconds = _compute_token_ttl(booking)
    raw_token, exp = issue_access_token(
        token_type=TokenType.GUEST_CHECKOUT,
        entity_id=booking_id,
        email=str(booking.get("guest_id") or ""),
        ttl_seconds=ttl_seconds,
    )

    token_hash = _hash_token(raw_token)

    # Record in access_tokens table
    record_token(
        tenant_id=tenant_id,
        token_type=TokenType.GUEST_CHECKOUT,
        entity_id=booking_id,
        raw_token=raw_token,
        exp=exp,
        email=str(booking.get("guest_id") or ""),
        metadata={
            "booking_id": booking_id,
            "generated_by": identity.get("user_id") or identity.get("sub") or "unknown",
            "property_id": booking.get("property_id"),
        },
        db=db,
    )

    # Store hash in booking_state for lookup
    try:
        db.table("booking_state").update({
            "guest_checkout_token_hash": token_hash,
            "updated_at_ms": _now_ms(),
        }).eq("booking_id", booking_id).eq("tenant_id", tenant_id).execute()
    except Exception as exc:
        logger.warning("guest_checkout: booking_state token_hash update failed: %s", exc)

    # Build portal URL (frontend route)
    base_url = os.environ.get("NEXT_PUBLIC_SITE_URL", "https://domaniqo-staging.vercel.app")
    portal_url = f"{base_url}/guest-checkout/{raw_token}"
    expires_at_iso = datetime.fromtimestamp(exp, tz=timezone.utc).isoformat()
    effective_date = _effective_checkout_date(booking)

    _audit(db, booking_id, tenant_id, "GUEST_CHECKOUT_TOKEN_GENERATED",
           identity.get("user_id") or "unknown",
           {
               "generated_by": identity.get("user_id") or "unknown",
               "portal_url": portal_url,
               "expires_at": expires_at_iso,
               "effective_checkout_date": effective_date,
           })

    return JSONResponse(status_code=200, content={
        "status":        "token_issued",
        "token":         raw_token,
        "portal_url":    portal_url,
        "qr_data":       portal_url,          # QR image: encode this string
        "expires_at":    expires_at_iso,
        "effective_checkout_date": effective_date,
        "guest_name":    booking.get("guest_name") or "Guest",
        "property_id":   booking.get("property_id"),
    })


# ===========================================================================
# GET /guest-checkout/{token}
# Public, token-gated. Returns portal state.
# ===========================================================================

@router_portal.get(
    "/guest-checkout/{token}",
    summary="Load guest checkout portal state (Phase 1045)",
    status_code=200,
)
async def get_guest_checkout_portal(
    token: str,
    client: Optional[Any] = None,
) -> JSONResponse:
    """
    Load the guest checkout portal.

    Returns:
    - Booking context (property name, checkout date, guest name)
    - Step definitions + completion status
    - Property contact info for the help/fallback path
    - Current confirmation status (already_confirmed vs pending)

    Marks guest_checkout_initiated_at on first access.
    """
    db = client or _get_db()
    claims, err = _verify_guest_checkout_token(token, db=db)
    if err:
        return make_error_response(status_code=401, code="TOKEN_INVALID", extra={"detail": err})

    booking_id = claims.get("entity_id")
    if not booking_id:
        return make_error_response(status_code=401, code="TOKEN_INVALID",
                                   extra={"detail": "Token does not reference a booking."})

    booking = _get_booking_for_portal(db, booking_id)
    if not booking:
        return make_error_response(status_code=404, code=ErrorCode.NOT_FOUND,
                                   extra={"detail": "Booking not found."})

    tenant_id = booking["tenant_id"]
    property_id = booking["property_id"]
    prop = _get_property_for_portal(db, property_id, tenant_id)

    # Mark initiation timestamp on first access (non-blocking)
    if not booking.get("guest_checkout_initiated_at"):
        try:
            db.table("booking_state").update({
                "guest_checkout_initiated_at": _now_iso(),
                "updated_at_ms": _now_ms(),
            }).eq("booking_id", booking_id).eq("tenant_id", tenant_id).execute()
        except Exception:
            pass

    steps_completed = booking.get("guest_checkout_steps_completed") or {}
    effective_date = _effective_checkout_date(booking)

    # Build step list for the portal
    steps = []
    for key in _CHECKOUT_STEPS:
        steps.append({
            "key":         key,
            "label":       _STEP_LABELS[key],
            "instruction": _STEP_INSTRUCTIONS[key],
            "optional":    key == "feedback",
            "completed":   bool(steps_completed.get(key)),
            "detail":      steps_completed.get(key),
        })

    already_confirmed = bool(booking.get("guest_checkout_confirmed_at"))
    required_complete = all(
        steps_completed.get(k)
        for k in _REQUIRED_FOR_COMPLETE
    )

    # Phase 1065B: check-in reference photos for proof-photo helper
    checkin_photos = _get_checkin_photos(db, booking_id)

    # Financial honesty: what still needs review after guest checkout
    deposit_status = booking.get("deposit_status") or "unknown"
    has_opening_meter = bool(booking.get("opening_meter"))

    return JSONResponse(status_code=200, content={
        "booking": {
            "booking_id":      booking["booking_id"],
            "guest_name":      booking.get("guest_name") or "Guest",
            "check_in":        str(booking.get("check_in", ""))[:10],
            "check_out":       str(booking.get("check_out", ""))[:10],
            "effective_checkout_date": effective_date,
            "is_early_checkout": bool(
                booking.get("early_checkout_approved") and booking.get("early_checkout_date")
            ),
        },
        "property": {
            "name":              (prop or {}).get("display_name") or property_id,
            "address":           (prop or {}).get("address"),
            "city":              (prop or {}).get("city"),
            "country":           (prop or {}).get("country"),
            "checkout_time":     (prop or {}).get("checkout_time") or "11:00",
            "emergency_contact": (prop or {}).get("emergency_contact"),
        },
        "steps":               steps,
        "steps_completed":     steps_completed,
        "required_complete":   required_complete,
        "required_for_complete": list(_REQUIRED_FOR_COMPLETE),
        "already_confirmed":   already_confirmed,
        "confirmed_at":        str(booking.get("guest_checkout_confirmed_at") or ""),
        "initiated_at":        str(booking.get("guest_checkout_initiated_at") or ""),
        # Phase 1065B: proof-photo helper
        "checkin_photos":      checkin_photos,
        # Phase 1065B: financial honesty context
        "deposit_status":      deposit_status,
        "has_opening_meter":   has_opening_meter,
    })



# ===========================================================================
# POST /guest-checkout/{token}/step/{step_key}
# Public, token-gated. Mark a single checkout step complete.
# ===========================================================================

@router_portal.post(
    "/guest-checkout/{token}/step/{step_key}",
    summary="Submit a guest checkout step (Phase 1045)",
    status_code=200,
)
async def submit_checkout_step(
    token: str,
    step_key: str,
    body: dict = {},
    client: Optional[Any] = None,
) -> JSONResponse:
    """
    Mark an individual checkout step as complete.

    Valid step_key values: confirm_departure, key_handover, feedback
    Body for 'feedback': { rating?: 1-5, comment?: string }
    Body for others: (none required)

    Idempotent — re-submitting overwrites previous value.
    """
    if step_key not in _CHECKOUT_STEPS:
        return make_error_response(
            status_code=400, code="UNKNOWN_STEP",
            extra={
                "detail": f"'{step_key}' is not a valid checkout step.",
                "valid_steps": _CHECKOUT_STEPS,
            },
        )

    db = client or _get_db()
    claims, err = _verify_guest_checkout_token(token, db=db)
    if err:
        return make_error_response(status_code=401, code="TOKEN_INVALID", extra={"detail": err})

    booking_id = claims.get("entity_id")
    if not booking_id:
        return make_error_response(status_code=401, code="TOKEN_INVALID",
                                   extra={"detail": "Invalid token."})

    booking = _get_booking_for_portal(db, booking_id)
    if not booking:
        return make_error_response(status_code=404, code=ErrorCode.NOT_FOUND,
                                   extra={"detail": "Booking not found."})

    tenant_id = booking["tenant_id"]
    steps = booking.get("guest_checkout_steps_completed") or {}
    now = _now_iso()

    # Build step detail payload
    step_detail: dict = {"completed_at": now}
    extra_booking_update: dict = {}  # Phase 1065B: additional booking_state fields

    if step_key == "feedback":
        rating = body.get("rating")
        comment = body.get("comment") or ""
        if rating is not None:
            try:
                r = int(rating)
                if 1 <= r <= 5:
                    step_detail["rating"] = r
            except (ValueError, TypeError):
                pass
        if comment:
            step_detail["comment"] = str(comment)[:500]
    elif step_key == "confirm_departure":
        step_detail["confirmed_by_guest"] = True
    elif step_key == "key_handover":
        method = str(body.get("method") or "confirmed")
        step_detail["method"] = method[:50]
    elif step_key == "ac_lights":
        step_detail["confirmed"] = True
        note = str(body.get("note") or "")[:200]
        if note:
            step_detail["note"] = note
    elif step_key == "doors_locked":
        step_detail["confirmed"] = True
        note = str(body.get("note") or "")[:200]
        if note:
            step_detail["note"] = note
    elif step_key == "contact_confirm":
        phone = str(body.get("phone") or "").strip()[:50] or None
        email = str(body.get("email") or "").strip()[:200] or None
        if not phone and not email:
            return make_error_response(
                status_code=400, code="CONTACT_REQUIRED",
                extra={"detail": "Please provide a phone number or email address for follow-up."},
            )
        step_detail["phone"] = phone
        step_detail["email"] = email
        if phone:
            extra_booking_update["guest_checkout_contact_phone"] = phone
        if email:
            extra_booking_update["guest_checkout_contact_email"] = email

    steps[step_key] = step_detail

    update_payload = {
        "guest_checkout_steps_completed": steps,
        "updated_at_ms": _now_ms(),
        **extra_booking_update,
    }

    try:
        db.table("booking_state").update(update_payload).eq("booking_id", booking_id).eq("tenant_id", tenant_id).execute()
    except Exception as exc:
        logger.error("guest_checkout: step update failed: %s", exc)
        return make_error_response(status_code=500, code="SERVER_ERROR",
                                   extra={"detail": "Failed to save step. Please try again."})

    return JSONResponse(status_code=200, content={
        "status":          "step_completed",
        "step_key":        step_key,
        "steps_completed": list(steps.keys()),
    })


# ===========================================================================
# POST /guest-checkout/{token}/complete
# Public, token-gated. Finalize guest checkout confirmation.
# ===========================================================================

@router_portal.post(
    "/guest-checkout/{token}/complete",
    summary="Finalize guest checkout confirmation (Phase 1045)",
    status_code=200,
)
async def complete_guest_checkout(
    token: str,
    client: Optional[Any] = None,
) -> JSONResponse:
    """
    Finalize guest self checkout.

    Requirements (Phase 1065B):
      confirm_departure, ac_lights, doors_locked, key_handover, contact_confirm
      feedback is always optional.

    Effect:
      - Writes guest_checkout_confirmed_at, used_guest_self_checkout=True,
        guest_checkout_summary (structured JSONB) to booking_state
      - Writes system-style chat message to guest_chat_messages (OM sees in stay thread)
      - Emits audit event GUEST_CHECKOUT_CONFIRMED
      - Returns: confirmed_at (exact UTC ISO timestamp), summary, pending_items, pending_notice

    Idempotent: re-calling returns existing confirmation payload.
    Does NOT affect booking_state.checked_out_at (worker settlement path).
    """
    db = client or _get_db()
    claims, err = _verify_guest_checkout_token(token, db=db)
    if err:
        return make_error_response(status_code=401, code="TOKEN_INVALID", extra={"detail": err})

    booking_id = claims.get("entity_id")
    if not booking_id:
        return make_error_response(status_code=401, code="TOKEN_INVALID",
                                   extra={"detail": "Invalid token."})

    booking = _get_booking_for_portal(db, booking_id)
    if not booking:
        return make_error_response(status_code=404, code=ErrorCode.NOT_FOUND,
                                   extra={"detail": "Booking not found."})

    tenant_id = booking["tenant_id"]
    property_id = booking.get("property_id", "")

    # Idempotent: already confirmed
    existing_confirmed_at = booking.get("guest_checkout_confirmed_at")
    if existing_confirmed_at:
        prop_info = _get_property_for_portal(db, property_id, tenant_id)
        property_name = (prop_info or {}).get("display_name") or "your property"
        return JSONResponse(status_code=200, content={
            "status":        "already_confirmed",
            "confirmed_at":  str(existing_confirmed_at),
            "property_name": property_name,
            "noop":          True,
            "summary":       booking.get("guest_checkout_summary"),
        })

    # Validate required steps
    steps = booking.get("guest_checkout_steps_completed") or {}
    missing = [k for k in _REQUIRED_FOR_COMPLETE if not steps.get(k)]
    if missing:
        return make_error_response(
            status_code=409, code="STEPS_INCOMPLETE",
            extra={
                "detail": "Please complete all required steps before confirming checkout.",
                "missing_steps": missing,
            },
        )

    now = _now_iso()
    effective_date = _effective_checkout_date(booking)

    # Financial honesty: what still needs team review after guest checkout
    deposit_status = booking.get("deposit_status") or "unknown"
    has_opening_meter = bool(booking.get("opening_meter"))
    pending_items = []
    if deposit_status not in ("returned", "waived", "na", "n/a", "none", "unknown"):
        pending_items.append("deposit_review")
    if has_opening_meter:
        pending_items.append("electricity_settlement")
    pending_items.append("property_inspection")

    # Contact from contact_confirm step
    contact_step = steps.get("contact_confirm") or {}
    contact_phone = contact_step.get("phone") or booking.get("guest_checkout_contact_phone")
    contact_email = contact_step.get("email") or booking.get("guest_checkout_contact_email")

    # Structured summary JSONB
    summary: dict = {
        "confirmed_at":             now,
        "effective_checkout_date":  effective_date,
        "steps_confirmed": {
            "confirmed_departure": bool(steps.get("confirm_departure")),
            "ac_lights_off":       bool(steps.get("ac_lights")),
            "doors_locked":        bool(steps.get("doors_locked")),
            "keys_returned":       bool(steps.get("key_handover")),
            "key_method":          (steps.get("key_handover") or {}).get("method"),
        },
        "contact_left": {
            "phone": contact_phone,
            "email": contact_email,
        },
        "feedback": {
            "rating":  (steps.get("feedback") or {}).get("rating"),
            "comment": (steps.get("feedback") or {}).get("comment"),
        } if steps.get("feedback") else None,
        "pending_items": pending_items,
    }

    try:
        db.table("booking_state").update({
            "guest_checkout_confirmed_at": now,
            "used_guest_self_checkout":    True,
            "guest_checkout_summary":      summary,
            "updated_at_ms":              _now_ms(),
        }).eq("booking_id", booking_id).eq("tenant_id", tenant_id).execute()
    except Exception as exc:
        logger.error("guest_checkout: confirmed_at write failed: %s", exc)
        return make_error_response(status_code=500, code="SERVER_ERROR",
                                   extra={"detail": "Failed to confirm checkout. Please try again."})

    _audit(db, booking_id, tenant_id, "GUEST_CHECKOUT_CONFIRMED",
           "guest",
           {
               "confirmed_at":            now,
               "effective_checkout_date": effective_date,
               "steps_confirmed":         summary["steps_confirmed"],
               "pending_items":           pending_items,
               "contact_left":            {"phone": bool(contact_phone), "email": bool(contact_email)},
               "used_guest_self_checkout": True,
           })

    # Phase 1065B: Write system chat message — OM sees full closure in stay thread
    prop_info = _get_property_for_portal(db, property_id, tenant_id)
    property_name = (prop_info or {}).get("display_name") or "the property"
    guest_name = booking.get("guest_name") or "Guest"

    checklist_lines = [
        f"  \u2022 AC & lights off: {'✓' if summary['steps_confirmed']['ac_lights_off'] else '\u2013'}",
        f"  \u2022 Doors locked:     {'✓' if summary['steps_confirmed']['doors_locked'] else '\u2013'}",
        f"  \u2022 Keys returned:    {'✓' if summary['steps_confirmed']['keys_returned'] else '\u2013'}",
    ]
    if summary["steps_confirmed"].get("key_method"):
        checklist_lines.append(f"  \u2022 Key method: {summary['steps_confirmed']['key_method']}")

    contact_lines = []
    if contact_phone:
        contact_lines.append(f"  \u2022 Phone: {contact_phone}")
    if contact_email:
        contact_lines.append(f"  \u2022 Email: {contact_email}")

    pending_readable = [p.replace("_", " ").title() for p in pending_items]
    pending_text = f"\nPending review: {', '.join(pending_readable)}" if pending_items else ""

    feedback_text = ""
    if summary.get("feedback"):
        fb = summary["feedback"]
        if fb and (fb.get("rating") or fb.get("comment")):
            feedback_text = "\nGuest feedback:"
            if fb.get("rating"):
                feedback_text += f" {'★' * fb['rating']}{'☆' * (5 - fb['rating'])}"
            if fb.get("comment"):
                feedback_text += f"\n  \u201c{str(fb['comment'])[:300]}\u201d"

    chat_content = (
        f"[Self Checkout Completed]\n"
        f"{guest_name} confirmed departure from {property_name}.\n"
        f"Completion time: {now}\n"
        f"Effective checkout date: {effective_date}\n\n"
        f"Guest confirmed:\n"
        + "\n".join(checklist_lines)
        + ("\n\nGuest follow-up contact:\n" + "\n".join(contact_lines) if contact_lines else "")
        + pending_text
        + feedback_text
        + "\n\nThis stay used guest self checkout."
    )

    try:
        from services.guest_messaging import resolve_conversation_owner
        assigned_om_id = resolve_conversation_owner(db, property_id, tenant_id)
    except Exception:
        assigned_om_id = tenant_id

    try:
        db.table("guest_chat_messages").insert({
            "booking_id":     booking_id,
            "property_id":    property_id,
            "tenant_id":      tenant_id,
            "sender_type":    "system",
            "message":        chat_content,
            "assigned_om_id": assigned_om_id,
        }).execute()
    except Exception as exc:
        logger.warning("guest_checkout: chat message write failed (non-blocking): %s", exc)

    # Pending notice for guest-facing response
    pending_notice = None
    review_items = [p for p in pending_items if p != "property_inspection"]
    if review_items:
        pending_notice = (
            "Our team will complete a final review including "
            + ", ".join([p.replace("_", " ") for p in review_items])
            + ". We'll contact you if anything needs clarifying."
        )

    return JSONResponse(status_code=200, content={
        "status":          "confirmed",
        "confirmed_at":    now,
        "guest_name":      guest_name,
        "property_name":   property_name,
        "summary":         summary,
        "pending_items":   pending_items,
        "pending_notice":  pending_notice,
        "message":         (
            f"Checkout confirmed. Thank you for a great stay at {property_name}!"
        ),
    })

