/**
 * Country data — static list with phone prefixes, currencies, and timezone mapping.
 *
 * Used by CountrySelect for:
 * - Searchable country dropdown
 * - Auto-detect country from browser timezone
 * - Phone prefix auto-fill
 * - Currency auto-select for Avg Nightly Rate
 */

export interface Country {
  code: string;       // ISO 3166-1 alpha-2
  name: string;
  phonePrefix: string;
  currency: string;
  currencySymbol: string;
}

/** Main country list — sorted alphabetically */
export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', phonePrefix: '+93', currency: 'AFN', currencySymbol: '؋' },
  { code: 'AL', name: 'Albania', phonePrefix: '+355', currency: 'ALL', currencySymbol: 'L' },
  { code: 'DZ', name: 'Algeria', phonePrefix: '+213', currency: 'DZD', currencySymbol: 'د.ج' },
  { code: 'AD', name: 'Andorra', phonePrefix: '+376', currency: 'EUR', currencySymbol: '€' },
  { code: 'AO', name: 'Angola', phonePrefix: '+244', currency: 'AOA', currencySymbol: 'Kz' },
  { code: 'AG', name: 'Antigua and Barbuda', phonePrefix: '+1-268', currency: 'XCD', currencySymbol: '$' },
  { code: 'AR', name: 'Argentina', phonePrefix: '+54', currency: 'ARS', currencySymbol: '$' },
  { code: 'AM', name: 'Armenia', phonePrefix: '+374', currency: 'AMD', currencySymbol: '֏' },
  { code: 'AU', name: 'Australia', phonePrefix: '+61', currency: 'AUD', currencySymbol: 'A$' },
  { code: 'AT', name: 'Austria', phonePrefix: '+43', currency: 'EUR', currencySymbol: '€' },
  { code: 'AZ', name: 'Azerbaijan', phonePrefix: '+994', currency: 'AZN', currencySymbol: '₼' },
  { code: 'BS', name: 'Bahamas', phonePrefix: '+1-242', currency: 'BSD', currencySymbol: '$' },
  { code: 'BH', name: 'Bahrain', phonePrefix: '+973', currency: 'BHD', currencySymbol: '.د.ب' },
  { code: 'BD', name: 'Bangladesh', phonePrefix: '+880', currency: 'BDT', currencySymbol: '৳' },
  { code: 'BB', name: 'Barbados', phonePrefix: '+1-246', currency: 'BBD', currencySymbol: '$' },
  { code: 'BY', name: 'Belarus', phonePrefix: '+375', currency: 'BYN', currencySymbol: 'Br' },
  { code: 'BE', name: 'Belgium', phonePrefix: '+32', currency: 'EUR', currencySymbol: '€' },
  { code: 'BZ', name: 'Belize', phonePrefix: '+501', currency: 'BZD', currencySymbol: '$' },
  { code: 'BJ', name: 'Benin', phonePrefix: '+229', currency: 'XOF', currencySymbol: 'CFA' },
  { code: 'BT', name: 'Bhutan', phonePrefix: '+975', currency: 'BTN', currencySymbol: 'Nu.' },
  { code: 'BO', name: 'Bolivia', phonePrefix: '+591', currency: 'BOB', currencySymbol: 'Bs.' },
  { code: 'BA', name: 'Bosnia and Herzegovina', phonePrefix: '+387', currency: 'BAM', currencySymbol: 'KM' },
  { code: 'BW', name: 'Botswana', phonePrefix: '+267', currency: 'BWP', currencySymbol: 'P' },
  { code: 'BR', name: 'Brazil', phonePrefix: '+55', currency: 'BRL', currencySymbol: 'R$' },
  { code: 'BN', name: 'Brunei', phonePrefix: '+673', currency: 'BND', currencySymbol: '$' },
  { code: 'BG', name: 'Bulgaria', phonePrefix: '+359', currency: 'BGN', currencySymbol: 'лв' },
  { code: 'BF', name: 'Burkina Faso', phonePrefix: '+226', currency: 'XOF', currencySymbol: 'CFA' },
  { code: 'BI', name: 'Burundi', phonePrefix: '+257', currency: 'BIF', currencySymbol: 'FBu' },
  { code: 'KH', name: 'Cambodia', phonePrefix: '+855', currency: 'KHR', currencySymbol: '៛' },
  { code: 'CM', name: 'Cameroon', phonePrefix: '+237', currency: 'XAF', currencySymbol: 'FCFA' },
  { code: 'CA', name: 'Canada', phonePrefix: '+1', currency: 'CAD', currencySymbol: 'C$' },
  { code: 'CV', name: 'Cape Verde', phonePrefix: '+238', currency: 'CVE', currencySymbol: '$' },
  { code: 'CF', name: 'Central African Republic', phonePrefix: '+236', currency: 'XAF', currencySymbol: 'FCFA' },
  { code: 'TD', name: 'Chad', phonePrefix: '+235', currency: 'XAF', currencySymbol: 'FCFA' },
  { code: 'CL', name: 'Chile', phonePrefix: '+56', currency: 'CLP', currencySymbol: '$' },
  { code: 'CN', name: 'China', phonePrefix: '+86', currency: 'CNY', currencySymbol: '¥' },
  { code: 'CO', name: 'Colombia', phonePrefix: '+57', currency: 'COP', currencySymbol: '$' },
  { code: 'KM', name: 'Comoros', phonePrefix: '+269', currency: 'KMF', currencySymbol: 'CF' },
  { code: 'CG', name: 'Congo', phonePrefix: '+242', currency: 'XAF', currencySymbol: 'FCFA' },
  { code: 'CR', name: 'Costa Rica', phonePrefix: '+506', currency: 'CRC', currencySymbol: '₡' },
  { code: 'HR', name: 'Croatia', phonePrefix: '+385', currency: 'EUR', currencySymbol: '€' },
  { code: 'CU', name: 'Cuba', phonePrefix: '+53', currency: 'CUP', currencySymbol: '$' },
  { code: 'CY', name: 'Cyprus', phonePrefix: '+357', currency: 'EUR', currencySymbol: '€' },
  { code: 'CZ', name: 'Czech Republic', phonePrefix: '+420', currency: 'CZK', currencySymbol: 'Kč' },
  { code: 'DK', name: 'Denmark', phonePrefix: '+45', currency: 'DKK', currencySymbol: 'kr' },
  { code: 'DJ', name: 'Djibouti', phonePrefix: '+253', currency: 'DJF', currencySymbol: 'Fdj' },
  { code: 'DM', name: 'Dominica', phonePrefix: '+1-767', currency: 'XCD', currencySymbol: '$' },
  { code: 'DO', name: 'Dominican Republic', phonePrefix: '+1-809', currency: 'DOP', currencySymbol: 'RD$' },
  { code: 'EC', name: 'Ecuador', phonePrefix: '+593', currency: 'USD', currencySymbol: '$' },
  { code: 'EG', name: 'Egypt', phonePrefix: '+20', currency: 'EGP', currencySymbol: 'E£' },
  { code: 'SV', name: 'El Salvador', phonePrefix: '+503', currency: 'USD', currencySymbol: '$' },
  { code: 'GQ', name: 'Equatorial Guinea', phonePrefix: '+240', currency: 'XAF', currencySymbol: 'FCFA' },
  { code: 'ER', name: 'Eritrea', phonePrefix: '+291', currency: 'ERN', currencySymbol: 'Nfk' },
  { code: 'EE', name: 'Estonia', phonePrefix: '+372', currency: 'EUR', currencySymbol: '€' },
  { code: 'SZ', name: 'Eswatini', phonePrefix: '+268', currency: 'SZL', currencySymbol: 'E' },
  { code: 'ET', name: 'Ethiopia', phonePrefix: '+251', currency: 'ETB', currencySymbol: 'Br' },
  { code: 'FJ', name: 'Fiji', phonePrefix: '+679', currency: 'FJD', currencySymbol: 'FJ$' },
  { code: 'FI', name: 'Finland', phonePrefix: '+358', currency: 'EUR', currencySymbol: '€' },
  { code: 'FR', name: 'France', phonePrefix: '+33', currency: 'EUR', currencySymbol: '€' },
  { code: 'GA', name: 'Gabon', phonePrefix: '+241', currency: 'XAF', currencySymbol: 'FCFA' },
  { code: 'GM', name: 'Gambia', phonePrefix: '+220', currency: 'GMD', currencySymbol: 'D' },
  { code: 'GE', name: 'Georgia', phonePrefix: '+995', currency: 'GEL', currencySymbol: '₾' },
  { code: 'DE', name: 'Germany', phonePrefix: '+49', currency: 'EUR', currencySymbol: '€' },
  { code: 'GH', name: 'Ghana', phonePrefix: '+233', currency: 'GHS', currencySymbol: '₵' },
  { code: 'GR', name: 'Greece', phonePrefix: '+30', currency: 'EUR', currencySymbol: '€' },
  { code: 'GD', name: 'Grenada', phonePrefix: '+1-473', currency: 'XCD', currencySymbol: '$' },
  { code: 'GT', name: 'Guatemala', phonePrefix: '+502', currency: 'GTQ', currencySymbol: 'Q' },
  { code: 'GN', name: 'Guinea', phonePrefix: '+224', currency: 'GNF', currencySymbol: 'FG' },
  { code: 'GW', name: 'Guinea-Bissau', phonePrefix: '+245', currency: 'XOF', currencySymbol: 'CFA' },
  { code: 'GY', name: 'Guyana', phonePrefix: '+592', currency: 'GYD', currencySymbol: '$' },
  { code: 'HT', name: 'Haiti', phonePrefix: '+509', currency: 'HTG', currencySymbol: 'G' },
  { code: 'HN', name: 'Honduras', phonePrefix: '+504', currency: 'HNL', currencySymbol: 'L' },
  { code: 'HK', name: 'Hong Kong', phonePrefix: '+852', currency: 'HKD', currencySymbol: 'HK$' },
  { code: 'HU', name: 'Hungary', phonePrefix: '+36', currency: 'HUF', currencySymbol: 'Ft' },
  { code: 'IS', name: 'Iceland', phonePrefix: '+354', currency: 'ISK', currencySymbol: 'kr' },
  { code: 'IN', name: 'India', phonePrefix: '+91', currency: 'INR', currencySymbol: '₹' },
  { code: 'ID', name: 'Indonesia', phonePrefix: '+62', currency: 'IDR', currencySymbol: 'Rp' },
  { code: 'IR', name: 'Iran', phonePrefix: '+98', currency: 'IRR', currencySymbol: '﷼' },
  { code: 'IQ', name: 'Iraq', phonePrefix: '+964', currency: 'IQD', currencySymbol: 'ع.د' },
  { code: 'IE', name: 'Ireland', phonePrefix: '+353', currency: 'EUR', currencySymbol: '€' },
  { code: 'IL', name: 'Israel', phonePrefix: '+972', currency: 'ILS', currencySymbol: '₪' },
  { code: 'IT', name: 'Italy', phonePrefix: '+39', currency: 'EUR', currencySymbol: '€' },
  { code: 'CI', name: 'Ivory Coast', phonePrefix: '+225', currency: 'XOF', currencySymbol: 'CFA' },
  { code: 'JM', name: 'Jamaica', phonePrefix: '+1-876', currency: 'JMD', currencySymbol: 'J$' },
  { code: 'JP', name: 'Japan', phonePrefix: '+81', currency: 'JPY', currencySymbol: '¥' },
  { code: 'JO', name: 'Jordan', phonePrefix: '+962', currency: 'JOD', currencySymbol: 'د.ا' },
  { code: 'KZ', name: 'Kazakhstan', phonePrefix: '+7', currency: 'KZT', currencySymbol: '₸' },
  { code: 'KE', name: 'Kenya', phonePrefix: '+254', currency: 'KES', currencySymbol: 'KSh' },
  { code: 'KI', name: 'Kiribati', phonePrefix: '+686', currency: 'AUD', currencySymbol: 'A$' },
  { code: 'KW', name: 'Kuwait', phonePrefix: '+965', currency: 'KWD', currencySymbol: 'د.ك' },
  { code: 'KG', name: 'Kyrgyzstan', phonePrefix: '+996', currency: 'KGS', currencySymbol: 'сом' },
  { code: 'LA', name: 'Laos', phonePrefix: '+856', currency: 'LAK', currencySymbol: '₭' },
  { code: 'LV', name: 'Latvia', phonePrefix: '+371', currency: 'EUR', currencySymbol: '€' },
  { code: 'LB', name: 'Lebanon', phonePrefix: '+961', currency: 'LBP', currencySymbol: 'ل.ل' },
  { code: 'LS', name: 'Lesotho', phonePrefix: '+266', currency: 'LSL', currencySymbol: 'L' },
  { code: 'LR', name: 'Liberia', phonePrefix: '+231', currency: 'LRD', currencySymbol: '$' },
  { code: 'LY', name: 'Libya', phonePrefix: '+218', currency: 'LYD', currencySymbol: 'ل.د' },
  { code: 'LI', name: 'Liechtenstein', phonePrefix: '+423', currency: 'CHF', currencySymbol: 'CHF' },
  { code: 'LT', name: 'Lithuania', phonePrefix: '+370', currency: 'EUR', currencySymbol: '€' },
  { code: 'LU', name: 'Luxembourg', phonePrefix: '+352', currency: 'EUR', currencySymbol: '€' },
  { code: 'MO', name: 'Macau', phonePrefix: '+853', currency: 'MOP', currencySymbol: 'MOP$' },
  { code: 'MG', name: 'Madagascar', phonePrefix: '+261', currency: 'MGA', currencySymbol: 'Ar' },
  { code: 'MW', name: 'Malawi', phonePrefix: '+265', currency: 'MWK', currencySymbol: 'MK' },
  { code: 'MY', name: 'Malaysia', phonePrefix: '+60', currency: 'MYR', currencySymbol: 'RM' },
  { code: 'MV', name: 'Maldives', phonePrefix: '+960', currency: 'MVR', currencySymbol: 'Rf' },
  { code: 'ML', name: 'Mali', phonePrefix: '+223', currency: 'XOF', currencySymbol: 'CFA' },
  { code: 'MT', name: 'Malta', phonePrefix: '+356', currency: 'EUR', currencySymbol: '€' },
  { code: 'MH', name: 'Marshall Islands', phonePrefix: '+692', currency: 'USD', currencySymbol: '$' },
  { code: 'MR', name: 'Mauritania', phonePrefix: '+222', currency: 'MRU', currencySymbol: 'UM' },
  { code: 'MU', name: 'Mauritius', phonePrefix: '+230', currency: 'MUR', currencySymbol: '₨' },
  { code: 'MX', name: 'Mexico', phonePrefix: '+52', currency: 'MXN', currencySymbol: '$' },
  { code: 'FM', name: 'Micronesia', phonePrefix: '+691', currency: 'USD', currencySymbol: '$' },
  { code: 'MD', name: 'Moldova', phonePrefix: '+373', currency: 'MDL', currencySymbol: 'L' },
  { code: 'MC', name: 'Monaco', phonePrefix: '+377', currency: 'EUR', currencySymbol: '€' },
  { code: 'MN', name: 'Mongolia', phonePrefix: '+976', currency: 'MNT', currencySymbol: '₮' },
  { code: 'ME', name: 'Montenegro', phonePrefix: '+382', currency: 'EUR', currencySymbol: '€' },
  { code: 'MA', name: 'Morocco', phonePrefix: '+212', currency: 'MAD', currencySymbol: 'د.م.' },
  { code: 'MZ', name: 'Mozambique', phonePrefix: '+258', currency: 'MZN', currencySymbol: 'MT' },
  { code: 'MM', name: 'Myanmar', phonePrefix: '+95', currency: 'MMK', currencySymbol: 'K' },
  { code: 'NA', name: 'Namibia', phonePrefix: '+264', currency: 'NAD', currencySymbol: '$' },
  { code: 'NR', name: 'Nauru', phonePrefix: '+674', currency: 'AUD', currencySymbol: 'A$' },
  { code: 'NP', name: 'Nepal', phonePrefix: '+977', currency: 'NPR', currencySymbol: '₨' },
  { code: 'NL', name: 'Netherlands', phonePrefix: '+31', currency: 'EUR', currencySymbol: '€' },
  { code: 'NZ', name: 'New Zealand', phonePrefix: '+64', currency: 'NZD', currencySymbol: 'NZ$' },
  { code: 'NI', name: 'Nicaragua', phonePrefix: '+505', currency: 'NIO', currencySymbol: 'C$' },
  { code: 'NE', name: 'Niger', phonePrefix: '+227', currency: 'XOF', currencySymbol: 'CFA' },
  { code: 'NG', name: 'Nigeria', phonePrefix: '+234', currency: 'NGN', currencySymbol: '₦' },
  { code: 'KP', name: 'North Korea', phonePrefix: '+850', currency: 'KPW', currencySymbol: '₩' },
  { code: 'MK', name: 'North Macedonia', phonePrefix: '+389', currency: 'MKD', currencySymbol: 'ден' },
  { code: 'NO', name: 'Norway', phonePrefix: '+47', currency: 'NOK', currencySymbol: 'kr' },
  { code: 'OM', name: 'Oman', phonePrefix: '+968', currency: 'OMR', currencySymbol: 'ر.ع.' },
  { code: 'PK', name: 'Pakistan', phonePrefix: '+92', currency: 'PKR', currencySymbol: '₨' },
  { code: 'PW', name: 'Palau', phonePrefix: '+680', currency: 'USD', currencySymbol: '$' },
  { code: 'PS', name: 'Palestine', phonePrefix: '+970', currency: 'ILS', currencySymbol: '₪' },
  { code: 'PA', name: 'Panama', phonePrefix: '+507', currency: 'PAB', currencySymbol: 'B/.' },
  { code: 'PG', name: 'Papua New Guinea', phonePrefix: '+675', currency: 'PGK', currencySymbol: 'K' },
  { code: 'PY', name: 'Paraguay', phonePrefix: '+595', currency: 'PYG', currencySymbol: '₲' },
  { code: 'PE', name: 'Peru', phonePrefix: '+51', currency: 'PEN', currencySymbol: 'S/.' },
  { code: 'PH', name: 'Philippines', phonePrefix: '+63', currency: 'PHP', currencySymbol: '₱' },
  { code: 'PL', name: 'Poland', phonePrefix: '+48', currency: 'PLN', currencySymbol: 'zł' },
  { code: 'PT', name: 'Portugal', phonePrefix: '+351', currency: 'EUR', currencySymbol: '€' },
  { code: 'QA', name: 'Qatar', phonePrefix: '+974', currency: 'QAR', currencySymbol: 'ر.ق' },
  { code: 'RO', name: 'Romania', phonePrefix: '+40', currency: 'RON', currencySymbol: 'lei' },
  { code: 'RU', name: 'Russia', phonePrefix: '+7', currency: 'RUB', currencySymbol: '₽' },
  { code: 'RW', name: 'Rwanda', phonePrefix: '+250', currency: 'RWF', currencySymbol: 'RF' },
  { code: 'KN', name: 'Saint Kitts and Nevis', phonePrefix: '+1-869', currency: 'XCD', currencySymbol: '$' },
  { code: 'LC', name: 'Saint Lucia', phonePrefix: '+1-758', currency: 'XCD', currencySymbol: '$' },
  { code: 'VC', name: 'Saint Vincent', phonePrefix: '+1-784', currency: 'XCD', currencySymbol: '$' },
  { code: 'WS', name: 'Samoa', phonePrefix: '+685', currency: 'WST', currencySymbol: 'T' },
  { code: 'SM', name: 'San Marino', phonePrefix: '+378', currency: 'EUR', currencySymbol: '€' },
  { code: 'ST', name: 'São Tomé and Príncipe', phonePrefix: '+239', currency: 'STN', currencySymbol: 'Db' },
  { code: 'SA', name: 'Saudi Arabia', phonePrefix: '+966', currency: 'SAR', currencySymbol: 'ر.س' },
  { code: 'SN', name: 'Senegal', phonePrefix: '+221', currency: 'XOF', currencySymbol: 'CFA' },
  { code: 'RS', name: 'Serbia', phonePrefix: '+381', currency: 'RSD', currencySymbol: 'дин.' },
  { code: 'SC', name: 'Seychelles', phonePrefix: '+248', currency: 'SCR', currencySymbol: '₨' },
  { code: 'SL', name: 'Sierra Leone', phonePrefix: '+232', currency: 'SLE', currencySymbol: 'Le' },
  { code: 'SG', name: 'Singapore', phonePrefix: '+65', currency: 'SGD', currencySymbol: 'S$' },
  { code: 'SK', name: 'Slovakia', phonePrefix: '+421', currency: 'EUR', currencySymbol: '€' },
  { code: 'SI', name: 'Slovenia', phonePrefix: '+386', currency: 'EUR', currencySymbol: '€' },
  { code: 'SB', name: 'Solomon Islands', phonePrefix: '+677', currency: 'SBD', currencySymbol: '$' },
  { code: 'SO', name: 'Somalia', phonePrefix: '+252', currency: 'SOS', currencySymbol: 'Sh' },
  { code: 'ZA', name: 'South Africa', phonePrefix: '+27', currency: 'ZAR', currencySymbol: 'R' },
  { code: 'KR', name: 'South Korea', phonePrefix: '+82', currency: 'KRW', currencySymbol: '₩' },
  { code: 'SS', name: 'South Sudan', phonePrefix: '+211', currency: 'SSP', currencySymbol: '£' },
  { code: 'ES', name: 'Spain', phonePrefix: '+34', currency: 'EUR', currencySymbol: '€' },
  { code: 'LK', name: 'Sri Lanka', phonePrefix: '+94', currency: 'LKR', currencySymbol: '₨' },
  { code: 'SD', name: 'Sudan', phonePrefix: '+249', currency: 'SDG', currencySymbol: 'ج.س.' },
  { code: 'SR', name: 'Suriname', phonePrefix: '+597', currency: 'SRD', currencySymbol: '$' },
  { code: 'SE', name: 'Sweden', phonePrefix: '+46', currency: 'SEK', currencySymbol: 'kr' },
  { code: 'CH', name: 'Switzerland', phonePrefix: '+41', currency: 'CHF', currencySymbol: 'CHF' },
  { code: 'SY', name: 'Syria', phonePrefix: '+963', currency: 'SYP', currencySymbol: '£' },
  { code: 'TW', name: 'Taiwan', phonePrefix: '+886', currency: 'TWD', currencySymbol: 'NT$' },
  { code: 'TJ', name: 'Tajikistan', phonePrefix: '+992', currency: 'TJS', currencySymbol: 'SM' },
  { code: 'TZ', name: 'Tanzania', phonePrefix: '+255', currency: 'TZS', currencySymbol: 'TSh' },
  { code: 'TH', name: 'Thailand', phonePrefix: '+66', currency: 'THB', currencySymbol: '฿' },
  { code: 'TL', name: 'Timor-Leste', phonePrefix: '+670', currency: 'USD', currencySymbol: '$' },
  { code: 'TG', name: 'Togo', phonePrefix: '+228', currency: 'XOF', currencySymbol: 'CFA' },
  { code: 'TO', name: 'Tonga', phonePrefix: '+676', currency: 'TOP', currencySymbol: 'T$' },
  { code: 'TT', name: 'Trinidad and Tobago', phonePrefix: '+1-868', currency: 'TTD', currencySymbol: 'TT$' },
  { code: 'TN', name: 'Tunisia', phonePrefix: '+216', currency: 'TND', currencySymbol: 'د.ت' },
  { code: 'TR', name: 'Turkey', phonePrefix: '+90', currency: 'TRY', currencySymbol: '₺' },
  { code: 'TM', name: 'Turkmenistan', phonePrefix: '+993', currency: 'TMT', currencySymbol: 'T' },
  { code: 'TV', name: 'Tuvalu', phonePrefix: '+688', currency: 'AUD', currencySymbol: 'A$' },
  { code: 'UG', name: 'Uganda', phonePrefix: '+256', currency: 'UGX', currencySymbol: 'USh' },
  { code: 'UA', name: 'Ukraine', phonePrefix: '+380', currency: 'UAH', currencySymbol: '₴' },
  { code: 'AE', name: 'United Arab Emirates', phonePrefix: '+971', currency: 'AED', currencySymbol: 'د.إ' },
  { code: 'GB', name: 'United Kingdom', phonePrefix: '+44', currency: 'GBP', currencySymbol: '£' },
  { code: 'US', name: 'United States', phonePrefix: '+1', currency: 'USD', currencySymbol: '$' },
  { code: 'UY', name: 'Uruguay', phonePrefix: '+598', currency: 'UYU', currencySymbol: '$U' },
  { code: 'UZ', name: 'Uzbekistan', phonePrefix: '+998', currency: 'UZS', currencySymbol: "so'm" },
  { code: 'VU', name: 'Vanuatu', phonePrefix: '+678', currency: 'VUV', currencySymbol: 'VT' },
  { code: 'VA', name: 'Vatican City', phonePrefix: '+39', currency: 'EUR', currencySymbol: '€' },
  { code: 'VE', name: 'Venezuela', phonePrefix: '+58', currency: 'VES', currencySymbol: 'Bs.S' },
  { code: 'VN', name: 'Vietnam', phonePrefix: '+84', currency: 'VND', currencySymbol: '₫' },
  { code: 'YE', name: 'Yemen', phonePrefix: '+967', currency: 'YER', currencySymbol: '﷼' },
  { code: 'ZM', name: 'Zambia', phonePrefix: '+260', currency: 'ZMW', currencySymbol: 'ZK' },
  { code: 'ZW', name: 'Zimbabwe', phonePrefix: '+263', currency: 'ZWL', currencySymbol: '$' },
];

/**
 * Timezone-to-country-code mapping.
 * Uses Intl.DateTimeFormat().resolvedOptions().timeZone for auto-detection.
 * Maps the primary timezone identifier (e.g. "Asia/Bangkok") to its country code.
 */
const TIMEZONE_TO_COUNTRY: Record<string, string> = {
  // Asia
  'Asia/Bangkok': 'TH', 'Asia/Tokyo': 'JP', 'Asia/Seoul': 'KR',
  'Asia/Shanghai': 'CN', 'Asia/Hong_Kong': 'HK', 'Asia/Taipei': 'TW',
  'Asia/Singapore': 'SG', 'Asia/Kuala_Lumpur': 'MY', 'Asia/Jakarta': 'ID',
  'Asia/Makassar': 'ID', 'Asia/Jayapura': 'ID',
  'Asia/Manila': 'PH', 'Asia/Ho_Chi_Minh': 'VN', 'Asia/Saigon': 'VN',
  'Asia/Phnom_Penh': 'KH', 'Asia/Vientiane': 'LA', 'Asia/Yangon': 'MM',
  'Asia/Kolkata': 'IN', 'Asia/Calcutta': 'IN', 'Asia/Mumbai': 'IN',
  'Asia/Colombo': 'LK', 'Asia/Dhaka': 'BD', 'Asia/Kathmandu': 'NP',
  'Asia/Karachi': 'PK', 'Asia/Kabul': 'AF',
  'Asia/Dubai': 'AE', 'Asia/Muscat': 'OM', 'Asia/Qatar': 'QA',
  'Asia/Bahrain': 'BH', 'Asia/Kuwait': 'KW', 'Asia/Riyadh': 'SA',
  'Asia/Baghdad': 'IQ', 'Asia/Tehran': 'IR',
  'Asia/Jerusalem': 'IL', 'Asia/Tel_Aviv': 'IL',
  'Asia/Amman': 'JO', 'Asia/Beirut': 'LB', 'Asia/Damascus': 'SY',
  'Asia/Tbilisi': 'GE', 'Asia/Yerevan': 'AM', 'Asia/Baku': 'AZ',
  'Asia/Almaty': 'KZ', 'Asia/Tashkent': 'UZ', 'Asia/Bishkek': 'KG',
  'Asia/Dushanbe': 'TJ', 'Asia/Ashgabat': 'TM',
  'Asia/Ulaanbaatar': 'MN', 'Asia/Brunei': 'BN',
  'Asia/Macau': 'MO',

  // Europe
  'Europe/London': 'GB', 'Europe/Dublin': 'IE',
  'Europe/Paris': 'FR', 'Europe/Berlin': 'DE', 'Europe/Madrid': 'ES',
  'Europe/Rome': 'IT', 'Europe/Amsterdam': 'NL', 'Europe/Brussels': 'BE',
  'Europe/Zurich': 'CH', 'Europe/Vienna': 'AT', 'Europe/Prague': 'CZ',
  'Europe/Warsaw': 'PL', 'Europe/Budapest': 'HU',
  'Europe/Bucharest': 'RO', 'Europe/Sofia': 'BG',
  'Europe/Athens': 'GR', 'Europe/Istanbul': 'TR',
  'Europe/Helsinki': 'FI', 'Europe/Stockholm': 'SE',
  'Europe/Oslo': 'NO', 'Europe/Copenhagen': 'DK',
  'Europe/Lisbon': 'PT', 'Europe/Tallinn': 'EE',
  'Europe/Riga': 'LV', 'Europe/Vilnius': 'LT',
  'Europe/Zagreb': 'HR', 'Europe/Ljubljana': 'SI',
  'Europe/Bratislava': 'SK', 'Europe/Belgrade': 'RS',
  'Europe/Sarajevo': 'BA', 'Europe/Podgorica': 'ME',
  'Europe/Skopje': 'MK', 'Europe/Kiev': 'UA', 'Europe/Kyiv': 'UA',
  'Europe/Moscow': 'RU', 'Europe/Minsk': 'BY',
  'Europe/Nicosia': 'CY', 'Europe/Reykjavik': 'IS',
  'Europe/Luxembourg': 'LU', 'Europe/Monaco': 'MC',
  'Europe/Malta': 'MT', 'Europe/Andorra': 'AD',
  'Europe/San_Marino': 'SM', 'Europe/Vatican': 'VA',
  'Europe/Chisinau': 'MD', 'Europe/Tirane': 'AL',
  'Europe/Vaduz': 'LI',

  // Americas
  'America/New_York': 'US', 'America/Chicago': 'US',
  'America/Denver': 'US', 'America/Los_Angeles': 'US',
  'America/Phoenix': 'US', 'America/Anchorage': 'US',
  'Pacific/Honolulu': 'US',
  'America/Toronto': 'CA', 'America/Vancouver': 'CA',
  'America/Edmonton': 'CA', 'America/Winnipeg': 'CA',
  'America/Halifax': 'CA', 'America/St_Johns': 'CA',
  'America/Mexico_City': 'MX', 'America/Cancun': 'MX', 'America/Tijuana': 'MX',
  'America/Sao_Paulo': 'BR', 'America/Manaus': 'BR', 'America/Fortaleza': 'BR',
  'America/Buenos_Aires': 'AR', 'America/Argentina/Buenos_Aires': 'AR',
  'America/Santiago': 'CL', 'America/Lima': 'PE',
  'America/Bogota': 'CO', 'America/Caracas': 'VE',
  'America/Guayaquil': 'EC', 'America/La_Paz': 'BO',
  'America/Asuncion': 'PY', 'America/Montevideo': 'UY',
  'America/Paramaribo': 'SR', 'America/Georgetown': 'GY',
  'America/Panama': 'PA', 'America/Costa_Rica': 'CR',
  'America/Guatemala': 'GT', 'America/Tegucigalpa': 'HN',
  'America/Managua': 'NI', 'America/El_Salvador': 'SV',
  'America/Belize': 'BZ', 'America/Havana': 'CU',
  'America/Jamaica': 'JM', 'America/Port-au-Prince': 'HT',
  'America/Santo_Domingo': 'DO', 'America/Port_of_Spain': 'TT',
  'America/Nassau': 'BS', 'America/Barbados': 'BB',

  // Africa
  'Africa/Cairo': 'EG', 'Africa/Johannesburg': 'ZA',
  'Africa/Lagos': 'NG', 'Africa/Nairobi': 'KE',
  'Africa/Dar_es_Salaam': 'TZ', 'Africa/Addis_Ababa': 'ET',
  'Africa/Accra': 'GH', 'Africa/Casablanca': 'MA',
  'Africa/Tunis': 'TN', 'Africa/Algiers': 'DZ',
  'Africa/Dakar': 'SN', 'Africa/Abidjan': 'CI',
  'Africa/Kampala': 'UG', 'Africa/Kigali': 'RW',
  'Africa/Lusaka': 'ZM', 'Africa/Harare': 'ZW',
  'Africa/Maputo': 'MZ', 'Africa/Windhoek': 'NA',
  'Africa/Gaborone': 'BW', 'Africa/Douala': 'CM',
  'Africa/Kinshasa': 'CG', 'Africa/Tripoli': 'LY',
  'Africa/Khartoum': 'SD', 'Africa/Mogadishu': 'SO',

  // Oceania
  'Australia/Sydney': 'AU', 'Australia/Melbourne': 'AU',
  'Australia/Brisbane': 'AU', 'Australia/Perth': 'AU',
  'Australia/Adelaide': 'AU', 'Australia/Darwin': 'AU',
  'Australia/Hobart': 'AU',
  'Pacific/Auckland': 'NZ', 'Pacific/Fiji': 'FJ',
  'Pacific/Tongatapu': 'TO', 'Pacific/Apia': 'WS',
  'Pacific/Port_Moresby': 'PG',

  // Indian Ocean
  'Indian/Maldives': 'MV', 'Indian/Mauritius': 'MU',
  'Indian/Mahe': 'SC',
};

/**
 * Auto-detect country code from browser timezone.
 * Falls back to undefined if detection fails.
 */
export function detectCountryCode(): string | undefined {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    return TIMEZONE_TO_COUNTRY[tz];
  } catch {
    return undefined;
  }
}

/** Find a Country object by its ISO code */
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code);
}

/** Search countries by name (case-insensitive prefix match) */
export function searchCountries(query: string): Country[] {
  if (!query.trim()) return COUNTRIES;
  const q = query.toLowerCase();
  return COUNTRIES.filter(c => c.name.toLowerCase().includes(q));
}
